[theme]
primaryColor = "#4A9002"               # زر أزرق عصري
backgroundColor = "#1E1E1E"            # خلفية داكنة
secondaryBackgroundColor = "#2C2C2C"   # خلفية البلوكات
textColor = "#FFFFFF"                  # لون النص
font = "sans serif"                    # نوع الخط
